language: node_js
node_js: 7.10.0
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
env:
  - CHROME_BIN=chromium-browser
cache:
  directories:
    - "app/node_modules"
script: cd app && npm install && npm test