version: "3"

services:
  java-bean:
    env_file: .env
    build: ./server
    depends_on:
      - db
    command: mvn spring-boot:run
    volumes:
     - "./server:/usr/src/server"
    ports:
      - "5000:8080"
  db:
    build: ./db
    env_file: .env
    ports: 
      - "5050:3306"
